# Generated by Django 2.0.7 on 2018-11-11 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stafftype', '0001_initial'),
        ('busdetails', '0010_remove_busdetails_mgr_id'),
        ('dailyrepo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyreports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('totalcollection', models.BigIntegerField()),
                ('wages', models.BigIntegerField()),
                ('fuel_quantity', models.IntegerField()),
                ('fuel_price', models.BigIntegerField()),
                ('fuel_total', models.BigIntegerField()),
                ('company', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=20)),
                ('phone', models.BigIntegerField()),
                ('extra_charge', models.BigIntegerField()),
                ('tyre_charge', models.BigIntegerField()),
                ('spare_parts', models.BigIntegerField()),
                ('other_expenses', models.BigIntegerField()),
                ('net_balance', models.BigIntegerField()),
                ('mgr_id', models.BigIntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdetails.Busdetails')),
                ('staff_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stafftype.Stafftype')),
            ],
        ),
    ]
