# Generated by Django 2.0.7 on 2018-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyrepo', '0002_dailyreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreports',
            name='totalcollection',
            field=models.IntegerField(),
        ),
    ]
