# Generated by Django 2.0.7 on 2018-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgname', models.CharField(default='', max_length=20)),
                ('psgage', models.CharField(default='', max_length=20)),
                ('psggender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('psgemail', models.CharField(default='', max_length=20)),
                ('psgcontact', models.CharField(default='', max_length=20)),
                ('psgusername', models.CharField(default='', max_length=20)),
                ('psgpassword', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
