# Generated by Django 2.0.7 on 2018-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psgemail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
