# Generated by Django 2.0.7 on 2018-11-06 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0002_auto_20181026_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbus',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
