# Generated by Django 2.0.7 on 2018-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(default='', max_length=20)),
                ('custage', models.CharField(default='', max_length=20)),
                ('custgender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('custemail', models.CharField(default='', max_length=30)),
                ('custcontact', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
