# Generated by Django 2.0.7 on 2018-11-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cust',
        ),
    ]
