# Generated by Django 2.0.7 on 2018-11-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custdetails', '0002_auto_20181118_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust',
            name='custcontact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cust',
            name='custemail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cust',
            name='custgender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
    ]
