# Generated by Django 2.0.7 on 2018-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasesdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(default='', max_length=20)),
                ('itemquantity', models.CharField(default='', max_length=20)),
                ('itembasicrate', models.CharField(default='', max_length=20)),
                ('itemunittotal', models.CharField(default='', max_length=20)),
                ('purchaseinvoice', models.BigIntegerField()),
            ],
        ),
    ]
