# Generated by Django 2.0.7 on 2018-11-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesdet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesdetails',
            name='total',
            field=models.CharField(default='', max_length=20),
        ),
    ]
