# Generated by Django 2.0.7 on 2018-11-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesdet', '0002_purchasesdetails_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesdetails',
            name='total',
        ),
    ]
