# Generated by Django 2.0.7 on 2018-11-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busdetails', '0012_auto_20181117_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_name', models.CharField(default='', max_length=20)),
                ('rate', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default=0, max_length=10)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdetails.Busdetails')),
            ],
        ),
    ]
