# Generated by Django 2.0.7 on 2018-08-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='seatorder',
            field=models.CharField(default='', max_length=20),
        ),
    ]
