# Generated by Django 2.0.7 on 2018-09-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0003_busdetails_mgr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='mgr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Managers'),
        ),
    ]
