# Generated by Django 2.0.7 on 2018-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0006_auto_20180914_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='mgr_id',
            field=models.BigIntegerField(),
        ),
    ]
