# Generated by Django 2.0.7 on 2018-10-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0007_auto_20180918_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='dropping_point',
            field=models.CharField(default='', max_length=30),
        ),
    ]
