# Generated by Django 2.0.7 on 2018-10-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0008_busdetails_dropping_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetails',
            name='dropping_point',
        ),
    ]
