# Generated by Django 2.0.7 on 2018-11-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0009_remove_busdetails_dropping_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetails',
            name='mgr_id',
        ),
    ]
