# Generated by Django 2.0.7 on 2018-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0010_remove_busdetails_mgr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='mgr_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
