# Generated by Django 2.0.7 on 2018-11-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0011_busdetails_mgr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='arrival_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='departure_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
