# Generated by Django 2.0.7 on 2018-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdetails', '0013_auto_20181121_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='arrival_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
