# Generated by Django 2.0.7 on 2018-11-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('duration', models.IntegerField()),
                ('seatcount', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('description', models.CharField(default='', max_length=20)),
                ('mgr_id', models.BigIntegerField()),
            ],
        ),
    ]
