# Generated by Django 2.0.7 on 2018-08-05 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [


    ]
