# Generated by Django 2.0.7 on 2018-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20181117_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='mgremail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
