# Generated by Django 2.0.7 on 2018-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0007_auto_20181120_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='mgrcontact',
            field=models.CharField(default='', max_length=5),
        ),
    ]
