# Generated by Django 2.0.7 on 2018-11-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_auto_20181120_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='mgrgender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
    ]
