# Generated by Django 2.0.7 on 2018-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_auto_20181120_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='mgrcontact',
            field=models.CharField(default='', max_length=10),
        ),
    ]
