# Generated by Django 2.0.7 on 2018-11-20 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(default='', max_length=20)),
                ('emphouse', models.CharField(default='', max_length=20)),
                ('empplace', models.CharField(default='', max_length=20)),
                ('empcity', models.CharField(default='', max_length=20)),
                ('empemail', models.EmailField(max_length=254)),
                ('empgender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('empdob', models.DateField(default=datetime.date.today)),
                ('empcontact', models.CharField(default='', max_length=5)),
                ('empdate_of_join', models.DateField(default=datetime.date.today)),
                ('empqualification', models.CharField(default='', max_length=20)),
                ('emp_licence_number', models.IntegerField()),
                ('licence_validity', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
