# Generated by Django 2.0.7 on 2018-11-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='mgr_id',
        ),
    ]
