# Generated by Django 2.0.7 on 2018-09-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busdetails', '0002_busdetails_seatorder'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackcontent', models.CharField(default='', max_length=50)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdetails.Busdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
