# Generated by Django 2.0.7 on 2018-09-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busdetails', '0002_busdetails_seatorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintcontent', models.CharField(default='', max_length=50)),
                ('user_id', models.BigIntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdetails.Busdetails')),
            ],
        ),
    ]
