# Generated by Django 2.0.7 on 2018-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20180913_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
